language: node_js
sudo: false
node_js: 
    - 12
branches:
    only:
    - master
cache:
    yarn: true
    directories:
      - node_modules    
jobs:
    fast_finish: true
    install:
        - "yarn install --production=false"
    script: 
        - yarn test:coverage --detectOpenHandles --forceExit --coverageReporters=text-lcov | ./node_modules/.bin/coveralls 
    deploy: &heroku
        provider: heroku
        app: $HEROKU_APP_NAME
        api_key: $HEROKU_APP_KEY
        on:
            repo: $HEROKU_APP_REPO